/********************************************************************
* ./include/Dictionary_DmpEvtNudHits.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ./include/Dictionary_DmpEvtNudHits.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableDictionary_DmpEvtNudHits();
extern void G__cpp_setup_inheritanceDictionary_DmpEvtNudHits();
extern void G__cpp_setup_typetableDictionary_DmpEvtNudHits();
extern void G__cpp_setup_memvarDictionary_DmpEvtNudHits();
extern void G__cpp_setup_globalDictionary_DmpEvtNudHits();
extern void G__cpp_setup_memfuncDictionary_DmpEvtNudHits();
extern void G__cpp_setup_funcDictionary_DmpEvtNudHits();
extern void G__set_cpp_environmentDictionary_DmpEvtNudHits();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "DmpEvtNudHits.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__Dictionary_DmpEvtNudHitsLN_TClass;
extern G__linked_taginfo G__Dictionary_DmpEvtNudHitsLN_TBuffer;
extern G__linked_taginfo G__Dictionary_DmpEvtNudHitsLN_TMemberInspector;
extern G__linked_taginfo G__Dictionary_DmpEvtNudHitsLN_TObject;
extern G__linked_taginfo G__Dictionary_DmpEvtNudHitsLN_vectorlEshortcOallocatorlEshortgRsPgR;
extern G__linked_taginfo G__Dictionary_DmpEvtNudHitsLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__Dictionary_DmpEvtNudHitsLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__Dictionary_DmpEvtNudHitsLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Dictionary_DmpEvtNudHitsLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__Dictionary_DmpEvtNudHitsLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Dictionary_DmpEvtNudHitsLN_DmpEvtNudHits;

/* STUB derived class for protected member access */
