//
// File generated by rootcint at Thu Dec 25 02:59:44 2014

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME dOdIincludedIDictionary_DmpEvtNudHits
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "Dictionary_DmpEvtNudHits.h"

#include "TCollectionProxyInfo.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void DmpEvtNudHits_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_DmpEvtNudHits(void *p = 0);
   static void *newArray_DmpEvtNudHits(Long_t size, void *p);
   static void delete_DmpEvtNudHits(void *p);
   static void deleteArray_DmpEvtNudHits(void *p);
   static void destruct_DmpEvtNudHits(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::DmpEvtNudHits*)
   {
      ::DmpEvtNudHits *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::DmpEvtNudHits >(0);
      static ::ROOT::TGenericClassInfo 
         instance("DmpEvtNudHits", ::DmpEvtNudHits::Class_Version(), "./include/DmpEvtNudHits.h", 13,
                  typeid(::DmpEvtNudHits), DefineBehavior(ptr, ptr),
                  &::DmpEvtNudHits::Dictionary, isa_proxy, 4,
                  sizeof(::DmpEvtNudHits) );
      instance.SetNew(&new_DmpEvtNudHits);
      instance.SetNewArray(&newArray_DmpEvtNudHits);
      instance.SetDelete(&delete_DmpEvtNudHits);
      instance.SetDeleteArray(&deleteArray_DmpEvtNudHits);
      instance.SetDestructor(&destruct_DmpEvtNudHits);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::DmpEvtNudHits*)
   {
      return GenerateInitInstanceLocal((::DmpEvtNudHits*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::DmpEvtNudHits*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *DmpEvtNudHits::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *DmpEvtNudHits::Class_Name()
{
   return "DmpEvtNudHits";
}

//______________________________________________________________________________
const char *DmpEvtNudHits::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::DmpEvtNudHits*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int DmpEvtNudHits::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::DmpEvtNudHits*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void DmpEvtNudHits::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::DmpEvtNudHits*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *DmpEvtNudHits::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::DmpEvtNudHits*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void DmpEvtNudHits::Streamer(TBuffer &R__b)
{
   // Stream an object of class DmpEvtNudHits.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(DmpEvtNudHits::Class(),this);
   } else {
      R__b.WriteClassBuffer(DmpEvtNudHits::Class(),this);
   }
}

//______________________________________________________________________________
void DmpEvtNudHits::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class DmpEvtNudHits.
      TClass *R__cl = ::DmpEvtNudHits::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fChannelID", (void*)&fChannelID);
      R__insp.InspectMember("vector<short>", (void*)&fChannelID, "fChannelID.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fEnergy", (void*)&fEnergy);
      R__insp.InspectMember("vector<double>", (void*)&fEnergy, "fEnergy.", false);
      TObject::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_DmpEvtNudHits(void *p) {
      return  p ? new(p) ::DmpEvtNudHits : new ::DmpEvtNudHits;
   }
   static void *newArray_DmpEvtNudHits(Long_t nElements, void *p) {
      return p ? new(p) ::DmpEvtNudHits[nElements] : new ::DmpEvtNudHits[nElements];
   }
   // Wrapper around operator delete
   static void delete_DmpEvtNudHits(void *p) {
      delete ((::DmpEvtNudHits*)p);
   }
   static void deleteArray_DmpEvtNudHits(void *p) {
      delete [] ((::DmpEvtNudHits*)p);
   }
   static void destruct_DmpEvtNudHits(void *p) {
      typedef ::DmpEvtNudHits current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::DmpEvtNudHits

namespace ROOT {
   void vectorlEdoublegR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlEdoublegR_Dictionary();
   static void *new_vectorlEdoublegR(void *p = 0);
   static void *newArray_vectorlEdoublegR(Long_t size, void *p);
   static void delete_vectorlEdoublegR(void *p);
   static void deleteArray_vectorlEdoublegR(void *p);
   static void destruct_vectorlEdoublegR(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const vector<double>*)
   {
      vector<double> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<double>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<double>", -2, "vector.dll", 0,
                  typeid(vector<double>), DefineBehavior(ptr, ptr),
                  0, &vectorlEdoublegR_Dictionary, isa_proxy, 0,
                  sizeof(vector<double>) );
      instance.SetNew(&new_vectorlEdoublegR);
      instance.SetNewArray(&newArray_vectorlEdoublegR);
      instance.SetDelete(&delete_vectorlEdoublegR);
      instance.SetDeleteArray(&deleteArray_vectorlEdoublegR);
      instance.SetDestructor(&destruct_vectorlEdoublegR);
      instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<double> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<double>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEdoublegR_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const vector<double>*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_vectorlEdoublegR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<double> : new vector<double>;
   }
   static void *newArray_vectorlEdoublegR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<double>[nElements] : new vector<double>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEdoublegR(void *p) {
      delete ((vector<double>*)p);
   }
   static void deleteArray_vectorlEdoublegR(void *p) {
      delete [] ((vector<double>*)p);
   }
   static void destruct_vectorlEdoublegR(void *p) {
      typedef vector<double> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class vector<double>

namespace ROOT {
   void vectorlEshortgR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlEshortgR_Dictionary();
   static void *new_vectorlEshortgR(void *p = 0);
   static void *newArray_vectorlEshortgR(Long_t size, void *p);
   static void delete_vectorlEshortgR(void *p);
   static void deleteArray_vectorlEshortgR(void *p);
   static void destruct_vectorlEshortgR(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const vector<short>*)
   {
      vector<short> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<short>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<short>", -2, "vector.dll", 0,
                  typeid(vector<short>), DefineBehavior(ptr, ptr),
                  0, &vectorlEshortgR_Dictionary, isa_proxy, 0,
                  sizeof(vector<short>) );
      instance.SetNew(&new_vectorlEshortgR);
      instance.SetNewArray(&newArray_vectorlEshortgR);
      instance.SetDelete(&delete_vectorlEshortgR);
      instance.SetDeleteArray(&deleteArray_vectorlEshortgR);
      instance.SetDestructor(&destruct_vectorlEshortgR);
      instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<short> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<short>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEshortgR_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const vector<short>*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_vectorlEshortgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<short> : new vector<short>;
   }
   static void *newArray_vectorlEshortgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<short>[nElements] : new vector<short>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEshortgR(void *p) {
      delete ((vector<short>*)p);
   }
   static void deleteArray_vectorlEshortgR(void *p) {
      delete [] ((vector<short>*)p);
   }
   static void destruct_vectorlEshortgR(void *p) {
      typedef vector<short> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class vector<short>

/********************************************************
* ./include/Dictionary_DmpEvtNudHits.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableDictionary_DmpEvtNudHits();

extern "C" void G__set_cpp_environmentDictionary_DmpEvtNudHits() {
  G__cpp_reset_tagtableDictionary_DmpEvtNudHits();
}
#include <new>
extern "C" int G__cpp_dllrevDictionary_DmpEvtNudHits() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* DmpEvtNudHits */
static int G__Dictionary_DmpEvtNudHits_168_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   DmpEvtNudHits* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new DmpEvtNudHits[n];
     } else {
       p = new((void*) gvp) DmpEvtNudHits[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new DmpEvtNudHits;
     } else {
       p = new((void*) gvp) DmpEvtNudHits;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__Dictionary_DmpEvtNudHitsLN_DmpEvtNudHits));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtNudHits_168_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((DmpEvtNudHits*) G__getstructoffset())->Reset();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtNudHits_168_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) DmpEvtNudHits::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtNudHits_168_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) DmpEvtNudHits::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtNudHits_168_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) DmpEvtNudHits::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtNudHits_168_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      DmpEvtNudHits::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtNudHits_168_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((DmpEvtNudHits*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtNudHits_168_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) DmpEvtNudHits::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtNudHits_168_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) DmpEvtNudHits::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtNudHits_168_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) DmpEvtNudHits::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtNudHits_168_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) DmpEvtNudHits::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__Dictionary_DmpEvtNudHits_168_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   DmpEvtNudHits* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new DmpEvtNudHits(*(DmpEvtNudHits*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__Dictionary_DmpEvtNudHitsLN_DmpEvtNudHits));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef DmpEvtNudHits G__TDmpEvtNudHits;
static int G__Dictionary_DmpEvtNudHits_168_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (DmpEvtNudHits*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((DmpEvtNudHits*) (soff+(sizeof(DmpEvtNudHits)*i)))->~G__TDmpEvtNudHits();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (DmpEvtNudHits*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((DmpEvtNudHits*) (soff))->~G__TDmpEvtNudHits();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__Dictionary_DmpEvtNudHits_168_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   DmpEvtNudHits* dest = (DmpEvtNudHits*) G__getstructoffset();
   *dest = *(DmpEvtNudHits*) libp->para[0].ref;
   const DmpEvtNudHits& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* DmpEvtNudHits */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncDictionary_DmpEvtNudHits {
 public:
  G__Sizep2memfuncDictionary_DmpEvtNudHits(): p(&G__Sizep2memfuncDictionary_DmpEvtNudHits::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncDictionary_DmpEvtNudHits::*p)();
};

size_t G__get_sizep2memfuncDictionary_DmpEvtNudHits()
{
  G__Sizep2memfuncDictionary_DmpEvtNudHits a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceDictionary_DmpEvtNudHits() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__Dictionary_DmpEvtNudHitsLN_DmpEvtNudHits))) {
     DmpEvtNudHits *G__Lderived;
     G__Lderived=(DmpEvtNudHits*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__Dictionary_DmpEvtNudHitsLN_DmpEvtNudHits),G__get_linked_tagnum(&G__Dictionary_DmpEvtNudHitsLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableDictionary_DmpEvtNudHits() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__Dictionary_DmpEvtNudHitsLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__Dictionary_DmpEvtNudHitsLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__Dictionary_DmpEvtNudHitsLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__Dictionary_DmpEvtNudHitsLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__Dictionary_DmpEvtNudHitsLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__Dictionary_DmpEvtNudHitsLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__Dictionary_DmpEvtNudHitsLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__Dictionary_DmpEvtNudHitsLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__Dictionary_DmpEvtNudHitsLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__Dictionary_DmpEvtNudHitsLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* DmpEvtNudHits */
static void G__setup_memvarDmpEvtNudHits(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__Dictionary_DmpEvtNudHitsLN_DmpEvtNudHits));
   { DmpEvtNudHits *p; p=(DmpEvtNudHits*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->fChannelID)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__Dictionary_DmpEvtNudHitsLN_vectorlEshortcOallocatorlEshortgRsPgR),G__defined_typename("vector<short>"),-1,1,"fChannelID=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fEnergy)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__Dictionary_DmpEvtNudHitsLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,1,"fEnergy=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__Dictionary_DmpEvtNudHitsLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarDictionary_DmpEvtNudHits() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncDmpEvtNudHits(void) {
   /* DmpEvtNudHits */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__Dictionary_DmpEvtNudHitsLN_DmpEvtNudHits));
   G__memfunc_setup("DmpEvtNudHits",1295,G__Dictionary_DmpEvtNudHits_168_0_1, 105, G__get_linked_tagnum(&G__Dictionary_DmpEvtNudHitsLN_DmpEvtNudHits), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Reset",515,G__Dictionary_DmpEvtNudHits_168_0_2, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__Dictionary_DmpEvtNudHits_168_0_3, 85, G__get_linked_tagnum(&G__Dictionary_DmpEvtNudHitsLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&DmpEvtNudHits::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__Dictionary_DmpEvtNudHits_168_0_4, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&DmpEvtNudHits::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__Dictionary_DmpEvtNudHits_168_0_5, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&DmpEvtNudHits::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__Dictionary_DmpEvtNudHits_168_0_6, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&DmpEvtNudHits::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__Dictionary_DmpEvtNudHitsLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__Dictionary_DmpEvtNudHits_168_0_10, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__Dictionary_DmpEvtNudHits_168_0_11, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&DmpEvtNudHits::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__Dictionary_DmpEvtNudHits_168_0_12, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&DmpEvtNudHits::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__Dictionary_DmpEvtNudHits_168_0_13, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&DmpEvtNudHits::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__Dictionary_DmpEvtNudHits_168_0_14, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&DmpEvtNudHits::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("DmpEvtNudHits", 1295, G__Dictionary_DmpEvtNudHits_168_0_15, (int) ('i'), G__get_linked_tagnum(&G__Dictionary_DmpEvtNudHitsLN_DmpEvtNudHits), -1, 0, 1, 1, 1, 0, "u 'DmpEvtNudHits' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~DmpEvtNudHits", 1421, G__Dictionary_DmpEvtNudHits_168_0_16, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__Dictionary_DmpEvtNudHits_168_0_17, (int) ('u'), G__get_linked_tagnum(&G__Dictionary_DmpEvtNudHitsLN_DmpEvtNudHits), -1, 1, 1, 1, 1, 0, "u 'DmpEvtNudHits' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncDictionary_DmpEvtNudHits() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalDictionary_DmpEvtNudHits() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcDictionary_DmpEvtNudHits() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__Dictionary_DmpEvtNudHitsLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtNudHitsLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtNudHitsLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtNudHitsLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtNudHitsLN_vectorlEshortcOallocatorlEshortgRsPgR = { "vector<short,allocator<short> >" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtNudHitsLN_vectorlEdoublecOallocatorlEdoublegRsPgR = { "vector<double,allocator<double> >" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtNudHitsLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtNudHitsLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtNudHitsLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtNudHitsLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtNudHitsLN_DmpEvtNudHits = { "DmpEvtNudHits" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableDictionary_DmpEvtNudHits() {
  G__Dictionary_DmpEvtNudHitsLN_TClass.tagnum = -1 ;
  G__Dictionary_DmpEvtNudHitsLN_TBuffer.tagnum = -1 ;
  G__Dictionary_DmpEvtNudHitsLN_TMemberInspector.tagnum = -1 ;
  G__Dictionary_DmpEvtNudHitsLN_TObject.tagnum = -1 ;
  G__Dictionary_DmpEvtNudHitsLN_vectorlEshortcOallocatorlEshortgRsPgR.tagnum = -1 ;
  G__Dictionary_DmpEvtNudHitsLN_vectorlEdoublecOallocatorlEdoublegRsPgR.tagnum = -1 ;
  G__Dictionary_DmpEvtNudHitsLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__Dictionary_DmpEvtNudHitsLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__Dictionary_DmpEvtNudHitsLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__Dictionary_DmpEvtNudHitsLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__Dictionary_DmpEvtNudHitsLN_DmpEvtNudHits.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableDictionary_DmpEvtNudHits() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtNudHitsLN_TClass);
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtNudHitsLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtNudHitsLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtNudHitsLN_TObject);
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtNudHitsLN_vectorlEshortcOallocatorlEshortgRsPgR);
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtNudHitsLN_vectorlEdoublecOallocatorlEdoublegRsPgR);
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtNudHitsLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtNudHitsLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtNudHitsLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtNudHitsLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtNudHitsLN_DmpEvtNudHits),sizeof(DmpEvtNudHits),-1,292096,(char*)NULL,G__setup_memvarDmpEvtNudHits,G__setup_memfuncDmpEvtNudHits);
}
extern "C" void G__cpp_setupDictionary_DmpEvtNudHits(void) {
  G__check_setup_version(30051515,"G__cpp_setupDictionary_DmpEvtNudHits()");
  G__set_cpp_environmentDictionary_DmpEvtNudHits();
  G__cpp_setup_tagtableDictionary_DmpEvtNudHits();

  G__cpp_setup_inheritanceDictionary_DmpEvtNudHits();

  G__cpp_setup_typetableDictionary_DmpEvtNudHits();

  G__cpp_setup_memvarDictionary_DmpEvtNudHits();

  G__cpp_setup_memfuncDictionary_DmpEvtNudHits();
  G__cpp_setup_globalDictionary_DmpEvtNudHits();
  G__cpp_setup_funcDictionary_DmpEvtNudHits();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncDictionary_DmpEvtNudHits();
  return;
}
class G__cpp_setup_initDictionary_DmpEvtNudHits {
  public:
    G__cpp_setup_initDictionary_DmpEvtNudHits() { G__add_setup_func("Dictionary_DmpEvtNudHits",(G__incsetup)(&G__cpp_setupDictionary_DmpEvtNudHits)); G__call_setup_funcs(); }
   ~G__cpp_setup_initDictionary_DmpEvtNudHits() { G__remove_setup_func("Dictionary_DmpEvtNudHits"); }
};
G__cpp_setup_initDictionary_DmpEvtNudHits G__cpp_setup_initializerDictionary_DmpEvtNudHits;

